postman stuff
HassanChowdhry/GoogleLinks pull request #2
Opened 2022-02-08 22:58 UTC by HassanChowdhry

2022-02-09 23:02 UTC, HassanChowdhry reviewed
Remove GoogleLinks.xlsx file

once u merge the other PR, raise this one against MASTER/Main

2022-02-09 23:02 UTC, HassanChowdhry commented on index.js
> +    // key
make .env file

2022-02-10 19:50 UTC, BilalIshtiaque requested changes
Boi

2022-02-10 19:50 UTC, BilalIshtiaque commented on .gitignore
> +.env
gud boi

2022-02-10 19:50 UTC, BilalIshtiaque commented on index.js
> +  const fileName = 'GoogleLinks.xlsx';
perhaps we can make the file name based on the search word used....name the file name based on what the user wants to search

2022-02-10 19:50 UTC, BilalIshtiaque commented on index.js
> +}
move this to another file and import it here :)

2022-02-10 19:53 UTC, HassanChowdhry commented on index.js
> +await searchNumberGetter();
tried that.
couldnt figure it out tho, will try again a bit later.

2022-02-11 03:03 UTC, BilalIshtiaque approved these changes
Looks good, add your ReadMe file as instructed in slack.

2022-02-11 03:03 UTC, BilalIshtiaque commented on index.js
> +})).search_number;
ideally we want validation that the user added something along that range. write a TODO to do that later

2022-02-11 03:03 UTC, BilalIshtiaque commented on index.js
> +//   .catch((error) => console.log('error', error));
not being used ? not gonna use in future ? Into the trash bin it goes! delete

2022-02-11 03:03 UTC, BilalIshtiaque commented on index.js
> +await loadSearchResults();
dont see why we need to put all this in a method, why not jst leave it bare in script ? just write a comment before the block of code that you are searching the result n etc...

2022-02-11 03:03 UTC, BilalIshtiaque commented on index.js
> +  const jsonResponse = await response.json();
u could combine this
(await fetch()).json()

2022-02-11 18:08 UTC, HassanChowdhry commented on ExcelUtils.js
> +  const fileName = `output/${name}.xlsx`;
what was the point of this?
It blocks the it blocks the creation of the excel file btw

2022-02-11 18:21 UTC, merged